# -*- coding: utf-8 -*-
"""automate_Dorothy Putri Elvira.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2wQ1Sml7ZGpLuFzXVI2C6OOyV7Ox4lz
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import os


def preprocess_data(file_path):

    print("Memuat dataset...")
    df = pd.read_csv(file_path, sep=';')

    print("Ukuran awal:", df.shape)

    # ==========================
    # Missing value handling
    # ==========================

    print("\nMenangani missing value...")

    df = df.drop('poutcome', axis=1)

    cat_cols = ['job', 'education', 'contact']

    for col in cat_cols:
        df[col] = df[col].fillna(
            df[col].mode()[0]
        )

    print(df.isnull().sum().sum(),
          "missing value tersisa")


    # ==========================
    # Hapus duplikat
    # ==========================

    print("\nMenghapus data duplikat...")

    before = df.shape[0]

    df = df.drop_duplicates()

    after = df.shape[0]

    print(
        f"Data terhapus: {before-after}"
    )


    # ==========================
    # Pisahkan fitur dan target
    # ==========================

    X = df.drop('y', axis=1)
    y = df['y']


    # ==========================
    # Encoding
    # ==========================

    print("\nEncoding fitur...")

    X = pd.get_dummies(
        X,
        drop_first=True
    )

    le = LabelEncoder()

    y = le.fit_transform(y)

    print(
        "Ukuran setelah encoding:",
        X.shape
    )


    # ==========================
    # Split
    # ==========================

    print("\nMembagi dataset...")

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    print(
        "Train:",
        X_train.shape
    )

    print(
        "Test:",
        X_test.shape
    )


    # ==========================
    # Scaling
    # ==========================

    print("\nMelakukan scaling...")

    scaler = StandardScaler()

    X_train = scaler.fit_transform(
        X_train
    )

    X_test = scaler.transform(
        X_test
    )


    # ==========================
    # Simpan hasil
    # ==========================

    os.makedirs(
        "dataset_preprocessing",
        exist_ok=True
    )

    pd.DataFrame(
        X_train
    ).to_csv(
        "dataset_preprocessing/X_train.csv",
        index=False
    )

    pd.DataFrame(
        X_test
    ).to_csv(
        "dataset_preprocessing/X_test.csv",
        index=False
    )

    pd.DataFrame(
        y_train
    ).to_csv(
        "dataset_preprocessing/y_train.csv",
        index=False
    )

    pd.DataFrame(
        y_test
    ).to_csv(
        "dataset_preprocessing/y_test.csv",
        index=False
    )

    print("\nPreprocessing selesai")


if __name__ == "__main__":

    preprocess_data(
        "/content/bank-full.csv"
    )